/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface QuizAttempt {
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
}
export interface QuizQuestion {
  'question' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  'addQuizQuestion' : ActorMethod<[string, Array<string>, bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getTopQuizScores' : ActorMethod<[], Array<[Principal, QuizAttempt]>>,
  'getUserQuizAttempts' : ActorMethod<[Principal], Array<QuizAttempt>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'submitQuizAttempt' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];