/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const QuizResult = IDL.Record({
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'timestamp' : Time,
});
export const QuizStats = IDL.Record({
  'totalCorrect' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'totalAttempts' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getQuizStats' : IDL.Func([], [QuizStats], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitQuizResult' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const QuizResult = IDL.Record({
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'timestamp' : Time,
  });
  const QuizStats = IDL.Record({
    'totalCorrect' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'totalAttempts' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getQuizStats' : IDL.Func([], [QuizStats], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitQuizResult' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };