/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const QuizAttempt = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addQuizQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getTopQuizScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, QuizAttempt))],
      ['query'],
    ),
  'getUserQuizAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitQuizAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const QuizAttempt = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addQuizQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getTopQuizScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, QuizAttempt))],
        ['query'],
      ),
    'getUserQuizAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitQuizAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };